<a href="https://colab.research.google.com/github/ehlatham/PUS2022_ELathamGray/blob/main/philly_arr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
arr = pd.read_csv("https://github.com/phillydao/phillydao-public-data/blob/main/docs/data/arrest_data_daily_by_zip.csv?raw=true")

In [8]:
arr.shape

(155918, 45)

In [7]:
arr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155918 entries, 0 to 155917
Data columns (total 45 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   date_value                                 155918 non-null  object
 1   ZCTA_GEOID                                 155918 non-null  object
 2   Aggravated Assault                         155918 non-null  int64
 3   Altered Firearm Serial Number              155918 non-null  int64
 4   Arson                                      155918 non-null  int64
 5   Auto Theft                                 155918 non-null  int64
 6   Burglary/Commercial                        155918 non-null  int64
 7   Burglary/Residential                       155918 non-null  int64
 8   Carjacking                                 155918 non-null  int64
 9   Criminal Mischief                          155918 non-null  int64
 10  Disorderly Conduct                         155918 non-null  int64
 11  Drug Possession                            155918 non-null  int64
 12  Drug Possession in Jails                   155918 non-null  int64
 13  Drug Sales                                 155918 non-null  int64
 14  Drug Sales with a Firearm                  155918 non-null  int64
 15  DUI                                        155918 non-null  int64
 16  Ethnic Intimidation                        155918 non-null  int64
 17  Firearm Possession by a Prohibited Person  155918 non-null  int64
 18  Firearm Possession without a License       155918 non-null  int64
 19  Fraud                                      155918 non-null  int64
 20  Homicide: Other                            155918 non-null  int64
 21  Homicide: Shooting                         155918 non-null  int64
 22  Illegal Dumping/Littering                  155918 non-null  int64
 23  Non-Fatal Shooting                         155918 non-null  int64
 24  Other Assaults                             155918 non-null  int64
 25  Other Firearm Offenses                     155918 non-null  int64
 26  Other Property Crimes                      155918 non-null  int64
 27  Other Violent Crimes                       155918 non-null  int64
 28  Patronizing Prostitutes/Sex Workers        155918 non-null  int64
 29  Promoting Prostitution                     155918 non-null  int64
 30  Prostitution/Sex Work                      155918 non-null  int64
 31  Rape                                       155918 non-null  int64
 32  Retail Theft                               155918 non-null  int64
 33  Robbery                                    155918 non-null  int64
 34  Robbery with a Deadly Weapon               155918 non-null  int64
 35  Sexual Assault and Other Sex Offenses      155918 non-null  int64
 36  Simple Assault                             155918 non-null  int64
 37  Strangulation                              155918 non-null  int64
 38  Theft                                      155918 non-null  int64
 39  Theft from Auto                            155918 non-null  int64
 40  Threats of Violence                        155918 non-null  int64
 41  Trespass                                   155918 non-null  int64
 42  Uncategorized Offenses                     155918 non-null  int64
 43  Victim/Witness Intimidation & Retaliation  155918 non-null  int64
 44  Violation of Protection Order              155918 non-null  int64
dtypes: int64(43), object(2)
memory usage: 53.5+ MB

In [9]:
arr

,date_value,ZCTA_GEOID,Aggravated Assault,Altered Firearm Serial Number,Arson,Auto Theft,Burglary/Commercial,Burglary/Residential,Carjacking,Criminal Mischief,...,Sexual Assault and Other Sex Offenses,Simple Assault,Strangulation,Theft,Theft from Auto,Threats of Violence,Trespass,Uncategorized Offenses,Victim/Witness Intimidation & Retaliation,Violation of Protection Order
0,2014-01-01,19102,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,2014-01-01,19103,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2014-01-01,19104,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,0
3,2014-01-01,19106,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2014-01-01,19107,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155913,2022-09-17,19151,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155914,2022-09-17,19152,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155915,2022-09-17,19153,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155916,2022-09-17,19154,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155917,2022-09-17,Unknown,3,0,0,4,0,0,0,2,...,0,0,0,5,1,0,1,2,0,1

In [17]:
arr[~(arr["ZCTA_GEOID"]=="Unkown")]["ZCTA_GEOID"].unique()

array(['19102', '19103', '19104', '19106', '19107', '19109', '19111',
       '19112', '19114', '19115', '19116', '19118', '19119', '19120',
       '19121', '19122', '19123', '19124', '19125', '19126', '19127',
       '19128', '19129', '19130', '19131', '19132', '19133', '19134',
       '19135', '19136', '19137', '19138', '19139', '19140', '19141',
       '19142', '19143', '19144', '19145', '19146', '19147', '19148',
       '19149', '19150', '19151', '19152', '19153', '19154', 'Unknown'],
      dtype=object)

In [19]:
arr.groupby("ZCTA_GEOID").sum()

,Aggravated Assault,Altered Firearm Serial Number,Arson,Auto Theft,Burglary/Commercial,Burglary/Residential,Carjacking,Criminal Mischief,Disorderly Conduct,Drug Possession,...,Sexual Assault and Other Sex Offenses,Simple Assault,Strangulation,Theft,Theft from Auto,Threats of Violence,Trespass,Uncategorized Offenses,Victim/Witness Intimidation & Retaliation,Violation of Protection Order
ZCTA_GEOID,,,,,,,,,,,,,,,,,,,,,
19102,228,0,5,11,96,15,5,57,24,259,...,36,102,9,242,1,88,52,589,9,10
19103,232,0,7,26,141,90,1,85,22,82,...,41,94,12,462,5,46,86,542,4,19
19104,863,1,25,75,116,343,24,124,6,851,...,76,284,71,808,4,125,66,1414,17,80
19106,148,0,11,14,75,49,4,53,1,66,...,17,41,5,211,5,38,12,369,2,1
19107,518,0,18,39,181,63,9,133,27,191,...,68,177,20,631,4,97,70,1069,69,12
19109,1,0,0,0,1,0,0,1,0,0,...,0,2,0,6,0,0,0,10,0,0
19111,463,0,6,48,43,189,13,98,2,194,...,64,240,74,271,16,105,34,309,13,181
19112,3,0,0,0,6,2,0,5,0,1,...,1,1,0,15,0,0,0,1,0,1
19114,244,1,5,24,59,48,5,34,2,29,...,26,109,30,185,6,44,12,137,7,80
19115,137,0,2,24,46,85,6,47,0,19,...,13,71,12,143,4,24,6,84,6,45
19116,147,0,2,22,22,81,4,26,0,22,...,12,65,11,140,5,32,8,84,1,42
19118,24,0,0,5,9,11,1,14,0,5,...,7,8,1,64,2,2,4,19,0,5
19119,209,0,5,16,12,92,5,52,0,160,...,6,87,30,117,4,33,8,164,7,46
19120,1168,1,25,95,104,292,23,156,5,644,...,83,433,112,334,13,203,59,891,20,180
19121,1188,0,19,99,51,356,22,152,3,765,...,70,318,88,271,12,164,39,1355,19,113
19122,330,0,7,49,65,122,9,64,2,414,...,42,102,28,282,5,61,16,399,2,51
19123,312,0,4,53,100,111,12,93,2,197,...,26,73,22,345,8,42,20,480,4,22
19124,1900,2,43,166,180,395,43,257,34,1649,...,163,639,181,665,11,296,132,2507,45,298
19125,356,0,8,109,58,247,18,133,4,608,...,20,117,15,506,13,66,20,888,4,44
19126,230,0,1,16,9,65,9,15,0,116,...,14,77,23,79,0,22,5,157,5,36
19127,39,0,1,10,10,19,1,9,0,2,...,4,22,1,35,5,7,3,26,0,9
19128,167,0,6,40,17,135,4,40,0,29,...,30,84,8,279,11,24,10,205,3,39
19129,118,0,3,34,31,54,6,17,1,54,...,11,50,8,139,4,20,4,114,2,35
19130,256,1,4,52,53,147,14,94,9,143,...,32,97,19,343,9,53,18,491,9,20
19131,868,2,12,64,78,143,32,112,3,726,...,37,313,66,320,6,140,51,1176,14,122
19132,1431,6,34,111,64,277,21,145,3,1493,...,68,408,124,250,5,158,62,2298,20,137
19133,1000,0,16,102,112,158,27,124,5,5716,...,58,261,68,229,2,139,41,1781,16,106
19134,2213,3,24,352,276,449,32,292,22,16809,...,128,642,162,778,8,341,148,3772,26,178
19135,633,0,14,63,49,194,9,138,7,323,...,45,282,65,327,5,128,49,586,18,198
19136,809,1,9,42,32,109,6,82,11,178,...,34,209,52,258,5,166,30,515,15,155
19137,128,0,8,26,101,41,4,50,3,27,...,7,64,15,218,2,40,10,134,6,46
19138,561,2,11,52,29,155,16,73,5,544,...,34,223,59,170,1,98,25,680,14,122
19139,1461,1,23,82,103,303,28,155,15,1631,...,68,504,155,281,7,194,67,2076,26,175
19140,1963,0,29,198,168,337,31,226,10,2564,...,119,564,153,429,7,314,77,2209,44,166
19141,843,0,17,61,65,190,29,123,8,953,...,39,339,77,227,5,145,25,1399,24,122
19142,836,0,12,66,33,205,24,78,3,568,...,40,286,77,220,2,100,36,833,33,93
19143,1610,7,26,87,65,334,34,175,16,816,...,68,610,160,353,8,226,70,1719,37,204
19144,889,3,21,62,92,269,13,126,3,1005,...,55,317,102,262,11,136,36,1152,13,122
19145,828,0,12,53,83,234,19,177,9,495,...,49,421,91,439,29,181,36,946,22,124
19146,695,0,14,40,42,268,15,153,1,596,...,32,299,79,396,25,127,33,909,12,82
19147,360,0,4,35,111,149,11,107,6,82,...,38,157,33,411,9,74,25,394,8,58
19148,823,0,11,60,157,222,8,161,9,523,...,60,402,67,697,21,171,49,1304,19,144
19149,709,0,11,95,62,160,20,162,5,189,...,55,352,97,422,18,137,33,656,15,205
19150,184,1,3,10,15,53,11,32,0,101,...,7,95,23,108,4,28,8,145,7,40
19151,445,0,12,24,22,99,12,52,3,279,...,15,158,45,131,0,69,25,404,6,77
19152,240,1,6,40,14,52,6,40,1,56,...,20,103,33,237,5,37,11,168,6,58
19153,200,1,2,169,68,36,19,28,0,56,...,13,50,17,194,0,24,16,106,4,23
19154,164,0,3,13,45,85,3,49,1,42,...,14,88,27,222,6,32,21,108,4,74
Unknown,861,7,28,5225,72,91,37,247,23,1094,...,154,264,31,2230,10,104,152,9622,30,48